# @immonex/doc-gen Konfiguration
# Docs: https://docs.immonex.de/doc-gen
# Source: https://npm.immonex.de/#/detail/@immonex/doc-gen
# Docsify-Konfiguration: https://docsify.js.org/#/configuration

title: Kickstart Team
subtitle: immonex Kickstart Team
description: immonex Kickstart Add-on für die Verarbeitung, Verknüpfung und Einbindung von OpenImmo-XML-basierten Immobilienmakler-Informationen und Kontaktformularen
keywords:
  - wordpress
  - plugin
  - immobilien
  - kontaktdaten
  - ansprechpartner
author: Carsten Scheuer

name: kickstart-team
permission: public
category: Plugins
use:
  - -zoomImage